name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: cachix/cachix-action@v15
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Fix keymap syntax issues from editor
        run: |
          echo "Checking and fixing keymap syntax issues..."
          
          # Fix common keymap editor syntax issues
          sed -i 's/^#$//' config/glove80.keymap || true
          sed -i 's/^endif {$/#endif/' config/glove80.keymap || true
          sed -i 's/^    \/$//g' config/glove80.keymap || true
          
          # Ensure proper #ifndef/#endif pairing
          if grep -q "#ifndef LAYER_Lower" config/glove80.keymap; then
            if ! grep -q "#endif" config/glove80.keymap; then
              sed -i '/^#ifndef LAYER_Lower/,/^#define LAYER_Lower 0/ a\#endif' config/glove80.keymap
            fi
          fi
          
          # Fix broken device tree root nodes
          sed -i 's/endif {$/\/ {/' config/glove80.keymap || true
          
          echo "Keymap syntax fixes applied"
          
          # Validate the fixed syntax
          cpp -E config/glove80.keymap > /dev/null 2>&1 && echo "✓ Keymap syntax is now valid" || echo "⚠ Warning: Some syntax issues may remain"
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: glove80.uf2
          path: glove80.uf2
